M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 03 Sep 2022 05:00:37 PM MST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-03T17:00:37-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1470
%
G90
G05
T1
X7.88Y-3.3701
T2
X8.125Y-2.625
T1
G00X3.1159Y-2.2687
M15
G01X3.1459Y-2.2687
M16
G05
T0
M30
